kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: hackathon-es
spec:
  host: hackathon-es-elastic.apps.hackathon.fuse.integration-qe.com
  to:
    kind: Service
    name: hackathon-es-default
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None