---
apiVersion: v1
kind: Service
metadata:
  name: quarkus-rest-server
  labels:
    app: quarkus-rest-server
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: quarkus-rest-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-rest-server
  labels:
    app: quarkus-rest-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quarkus-rest-server
  template:
    metadata:
      labels:
        app: quarkus-rest-server
    spec:
      containers:
        - name: quarkus-rest-server
          image: quay.io/fuse_qe/quarkus-rest-server:1.0.0
          ports:
            - containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: quarkus-rest-server
  labels:
    app: quarkus-rest-server
spec:
  to:
    kind: Service
    name: quarkus-rest-server
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
