---
apiVersion: v1
kind: Service
metadata:
  name: fhir-dstu3-auth
  labels:
    app: fhir-dstu3-auth
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: fhir-dstu3-auth
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fhir-dstu3-auth
  labels:
    app: fhir-dstu3-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fhir-dstu3-auth
  template:
    metadata:
      labels:
        app: fhir-dstu3-auth
    spec:
      containers:
        - name: fhir
          image: quay.io/fuse_qe/hapi-fhir:v8.2.0
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: FHIR_VERSION
              value: "DSTU3"
            - name: AUTH_ENABLED
              value: "true"
            - name: AUTH_USERNAME
              value: "admin"
            - name: AUTH_PASSWORD
              value: "admin"
          livenessProbe:
            httpGet:
              path: /fhir/metadata
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /fhir/metadata
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: fhir-dstu3-auth
  labels:
    app: fhir-dstu3-auth
spec:
  to:
    kind: Service
    name: fhir-dstu3-auth
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
